Ingredient.create(name: "---", genre_id: "0")
Ingredient.create(name: "牛肉 (g)", genre_id: "1")
Ingredient.create(name: "豚肉 (g)", genre_id: "1")
Ingredient.create(name: "鶏肉 (g)", genre_id: "1")
Ingredient.create(name: "ひき肉 (g)", genre_id: "1")
Ingredient.create(name: "---", genre_id: "2")
Ingredient.create(name: "玉ねぎ (個)", genre_id: "3")
Ingredient.create(name: "じゃがいも (個)", genre_id: "3")
Ingredient.create(name: "にんじん (本)", genre_id: "3")
Ingredient.create(name: "セロリ (本)", genre_id: "3")
Ingredient.create(name: "ナス (本)", genre_id: "3")
Ingredient.create(name: "トマト (個)", genre_id: "3")
Ingredient.create(name: "きゅうり (本)", genre_id: "3")
Ingredient.create(name: "レタス (個)", genre_id: "3")
Ingredient.create(name: "キャベツ (個)", genre_id: "3")
Ingredient.create(name: "ブロッコリー (個)", genre_id: "3")
Ingredient.create(name: "ピーマン (個)", genre_id: "3")
Ingredient.create(name: "カラーピーマン (個)", genre_id: "3")
Ingredient.create(name: "ズッキーニ (本)", genre_id: "3")
Ingredient.create(name: "しめじ (パック)", genre_id: "3")
Ingredient.create(name: "ニンニク (片)", genre_id: "3")
Ingredient.create(name: "---", genre_id: "4")
Ingredient.create(name: "卵 (個)", genre_id: "5")
Ingredient.create(name: "牛乳 (cc)", genre_id: "5")
Ingredient.create(name: "チーズ (g)", genre_id: "5")
Ingredient.create(name: "バター (g)", genre_id: "5")
Ingredient.create(name: "ヨーグルト (cc)", genre_id: "5")
Ingredient.create(name: "クリーム (cc)", genre_id: "5")
Ingredient.create(name: "練乳 (cc)", genre_id: "5")
Ingredient.create(name: "---", genre_id: "6")
Ingredient.create(name: "米 (g)", genre_id: "7")
Ingredient.create(name: "食パン (枚)", genre_id: "7")
Ingredient.create(name: "スパゲティ (g)", genre_id: "7")
Ingredient.create(name: "小麦粉 (g)", genre_id: "7")
Ingredient.create(name: "---", genre_id: "8")
Ingredient.create(name: "ケチャップ (大さじ)", genre_id: "9")
Ingredient.create(name: "マヨネーズ (大さじ)", genre_id: "9")
Ingredient.create(name: "しょうゆ (大さじ)", genre_id: "9")
Ingredient.create(name: "お酢 (大さじ)", genre_id: "9")
Ingredient.create(name: "みりん (大さじ)", genre_id: "9")
Ingredient.create(name: "料理酒 (大さじ)", genre_id: "9")
Ingredient.create(name: "サラダ油 (大さじ)", genre_id: "9")
Ingredient.create(name: "ごま油 (大さじ)", genre_id: "9")
Ingredient.create(name: "塩 (小さじ)", genre_id: "9")
Ingredient.create(name: "こしょう (小さじ)", genre_id: "9")
Ingredient.create(name: "コンソメ (キューブ)", genre_id: "9")
Ingredient.create(name: "ソース (大さじ)", genre_id: "9")
Ingredient.create(name: "マスタード (大さじ)", genre_id: "9")